import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import { cn } from "@/lib/utils";
import { Header } from "./components/header/Header";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { Analytics } from "@vercel/analytics/react";

const satoshi = localFont({
  src: "./Satoshi-Variable.woff2",
  display: "swap",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" style={{ scrollBehavior: "smooth" }}>
      <body
        className={cn(
          "antialiased bg-[#121212] min-h-[100vh] text-white",
          satoshi.className
        )}
      >
        <Header />
        {children}
        <Analytics />
        <SpeedInsights />
        <div className="h-24 w-1"></div>
      </body>
    </html>
  );
}
