import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import { cn } from "@/lib/utils";
import { ClerkProvider } from "@clerk/nextjs";
import { frFR } from "@clerk/localizations";
import { dark } from "@clerk/themes";
import { Header } from "./components/header/Header";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { Analytics } from "@vercel/analytics/react";

const satoshi = localFont({
	src: "./Satoshi-Variable.woff2",
	display: "swap",
});
export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<ClerkProvider
			localization={frFR}
			appearance={{
				baseTheme: dark,
			}}
		>
			<html lang="en" style={{ scrollBehavior: "smooth" }}>
				<body
					className={cn(
						"antialiased bg-[#121212] text-white",
						satoshi.className
					)}
				>
					<Header />
					{children}
					<Analytics />
					<SpeedInsights />
				</body>
			</html>
		</ClerkProvider>
	);
}
